- hosts: web
  become: yes
  tasks:
    - include_role:
        name: dev
      vars:
        users: MmBatteries
        password: password
        shell: zsh
    - include_role:
        name: installs/dockerInstall
      vars:
        users: MmBatteries
    - include_role:
        name: installs/nginxInstall
- hosts: jenkins
  tasks:
   - include_role:
       name: installs/jenkinsInstall
