- hosts: web
  tasks:
    - include_role:
        name: installs/dockerInstall
      vars:
        nodes: web
    - include_role:
        name: dev
      vars:
        users: MmBatteries
        password: password
        shell: zsh
        nodes: web
