- name: get dockerinstall file
  shell:
    cmd: curl -fsSl https://get.docker.com -o get-docker.sh
  become: yes
- name: install docker
  shell:
    cmd: bash get-docker.sh
  become:  yes
- name: mod user
  shell:
    cmd: sudo usermod -aG docker {{users}}
  become: yes
