- name: get dockerinstall file
  shell:
    cmd: cmd -fsSL https://get.docker.com -o get-docker.sh
- name: install docker
  shell:
    cmd: sudo bash get-docker.sh
- name: add docker grouo
  shell:
    cmd: sudo groupadd docker
- name: mod user
  shell: 
    cmd: sudo usermod -aG docker {{user}}
- name: restart group
  shell:
    cmd: newgrp docker
