- name: Run shell install
  import_role:
    name: installs/{{shell}}Install
  become: yes
- name: Run Curl install
  import_role:
    name: installs/curlInstall
  become: yes
- name: add dev group
  group:
    name: dev
    state: present
  become: yes
- name: add users
  user:
    name: "{{users}}"
    password: "{{passwords}}"
    shell: /bin/"{{shell}}"
    group: dev
  become: yes
      
